In [0]:
#https://sites.temple.edu/tudsc/2017/03/30/measuring-similarity-between-texts-in-python/

In [0]:
d1 = "plot: two teen couples go to a church party, drink and then drive."
d2 = "films adapted from comic books have had plenty of success , whether they're about superheroes ( batman , superman , spawn ) , or geared toward kids ( casper ) or the arthouse crowd ( ghost world ) , but there's never really been a comic book like from hell before . "
d3 = "every now and then a movie comes along from a suspect studio , with every indication that it will be a stinker , and to everybody's surprise ( perhaps even the studio ) the film becomes a critical darling . "
d4 = "damn that y2k bug . "
d5 = "plot: two teen couples go to a church party, drink and then drive."

In [0]:
documents = [d1, d2, d3, d4, d5]

In [0]:
type(documents)

list

In [0]:
documents

['plot: two teen couples go to a church party, drink and then drive.',
 "films adapted from comic books have had plenty of success , whether they're about superheroes ( batman , superman , spawn ) , or geared toward kids ( casper ) or the arthouse crowd ( ghost world ) , but there's never really been a comic book like from hell before . ",
 "every now and then a movie comes along from a suspect studio , with every indication that it will be a stinker , and to everybody's surprise ( perhaps even the studio ) the film becomes a critical darling . ",
 'damn that y2k bug . ']

# Normalize

## Stemming

In [0]:
import nltk, string, numpy

nltk.download('punkt') # first-time use only

stemmer = nltk.stem.porter.PorterStemmer()

[nltk_data] Downloading package punkt to /content/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [0]:
def StemTokens(tokens):
  return [stemmer.stem(token) for token in tokens]

remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)

def StemNormalize(text):
  return StemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

## Lemmatization

In [0]:
nltk.download('wordnet') # first-time use only

lemmer = nltk.stem.WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /content/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [0]:
def LemTokens(tokens):
  return [lemmer.lemmatize(token) for token in tokens]

remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)

def LemNormalize(text):
  return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

## Text to vectors of term frequency

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

LemVectorizer = CountVectorizer(tokenizer=LemNormalize, stop_words='english')
LemVectorizer.fit_transform(documents)

<4x41 sparse matrix of type '<class 'numpy.int64'>'
	with 42 stored elements in Compressed Sparse Row format>

In [0]:
LemVectorizer.vocabulary_

{'adapted': 0,
 'arthouse': 1,
 'batman': 2,
 'book': 3,
 'bug': 4,
 'casper': 5,
 'church': 6,
 'come': 7,
 'comic': 8,
 'couple': 9,
 'critical': 10,
 'crowd': 11,
 'damn': 12,
 'darling': 13,
 'drink': 14,
 'drive': 15,
 'everybodys': 16,
 'film': 17,
 'geared': 18,
 'ghost': 19,
 'hell': 20,
 'indication': 21,
 'kid': 22,
 'like': 23,
 'movie': 24,
 'party': 25,
 'plenty': 26,
 'plot': 27,
 'really': 28,
 'spawn': 29,
 'stinker': 30,
 'studio': 31,
 'success': 32,
 'superheroes': 33,
 'superman': 34,
 'surprise': 35,
 'suspect': 36,
 'teen': 37,
 'theyre': 38,
 'world': 39,
 'y2k': 40}

In [0]:
tf_matrix = LemVectorizer.transform(documents).toarray()
tf_matrix

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 2, 0, 1, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
        1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

## Get IDF

In [0]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidfTran = TfidfTransformer(norm = "l2")
tfidfTran.fit(tf_matrix)

tfidfTran.idf_

array([1.91629073, 1.91629073, 1.91629073, 1.91629073, 1.91629073,
       1.91629073, 1.91629073, 1.91629073, 1.91629073, 1.91629073,
       1.91629073, 1.91629073, 1.91629073, 1.91629073, 1.91629073,
       1.91629073, 1.91629073, 1.51082562, 1.91629073, 1.91629073,
       1.91629073, 1.91629073, 1.91629073, 1.91629073, 1.91629073,
       1.91629073, 1.91629073, 1.91629073, 1.91629073, 1.91629073,
       1.91629073, 1.91629073, 1.91629073, 1.91629073, 1.91629073,
       1.91629073, 1.91629073, 1.91629073, 1.91629073, 1.91629073,
       1.91629073])

In [0]:
import math

def idf(n,df):
    result = math.log((n+1.0)/(df+1.0)) + 1
    return result

print("The idf for terms that appear in one document: " + str(idf(4,1)))
print("The idf for terms that appear in two documents: " + str(idf(4,2)))

The idf for terms that appear in one document: 1.916290731874155
The idf for terms that appear in two documents: 1.5108256237659907


In [0]:
tfidf_matrix = tfidfTran.transform(tf_matrix)
tfidf_matrix.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.37796447, 0.        , 0.        , 0.37796447,
        0.        , 0.        , 0.        , 0.        , 0.37796447,
        0.37796447, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37796447, 0.        , 0.37796447, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.37796447, 0.        , 0.        ,
        0.        ],
       [0.19381304, 0.19381304, 0.19381304, 0.38762607, 0.        ,
        0.19381304, 0.        , 0.        , 0.38762607, 0.        ,
        0.        , 0.19381304, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.15280442, 0.19381304, 0.19381304,
        0.19381304, 0.        , 0.19381304, 0.19381304, 0.        ,
        0.        , 0.19381304, 0.        , 0.19381304, 0.19381304,
        0.        , 0.     

# SKLearn implementation

Scikit-learn actually has another function TfidfVectorizer that combines the work of CountVectorizer and TfidfTransformer, which makes the process more efficient.

In [0]:
from google.colab import files
uploaded = files.upload()

Saving RTM_SDIVM_27_Master_Data_Change_Management v16_R5.xlsx to RTM_SDIVM_27_Master_Data_Change_Management v16_R5.xlsx


In [0]:
import pandas as pd
data = pd.read_excel('RTM_SDIVM_27_Master_Data_Change_Management v16_R5.xlsx', sheet_name = 'L1 Requirements')
data = data[data.Status != 'Cancelled']
data['text'] = data['Description \n(Stakeholder: I want to <goal or need>)'].astype(str) + data['So that <Justification> ']
req = data[['Requirement ID', 'text']]
req = req.dropna(how = 'all')

req.shape

(107, 2)

In [0]:
req.isnull().any()

Requirement ID    False
text              False
dtype: bool

In [0]:
reqs = req['text'].values

In [0]:
import pandas as pd

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')

def cos_similarity(textlist):
    tfidf = TfidfVec.fit_transform(textlist)
    return (tfidf * tfidf.T).toarray()

similarity = pd.DataFrame(cos_similarity(reqs))

In [0]:
similarity.isnull().any()

0                 False
1                 False
2                 False
3                 False
4                 False
5                 False
6                 False
7                 False
8                 False
9                 False
10                False
11                False
12                False
13                False
14                False
15                False
16                False
17                False
18                False
19                False
20                False
21                False
22                False
23                False
24                False
25                False
26                False
27                False
28                False
29                False
                  ...  
78                False
79                False
80                False
81                False
82                False
83                False
84                False
85                False
86                False
87                False
88              

In [0]:
similarity['Requirement ID'] = req['Requirement ID']

#similarity.columns = similarity['Requirement ID']

similarity

0         1         2         3         4         5         6  \
0    1.000000  0.059825  0.236718  0.122481  0.122457  0.019233  0.000000   
1    0.059825  1.000000  0.245718  0.141825  0.093937  0.063173  0.039171   
2    0.236718  0.245718  1.000000  0.204091  0.131672  0.055768  0.034579   
3    0.122481  0.141825  0.204091  1.000000  0.168585  0.128889  0.061039   
4    0.122457  0.093937  0.131672  0.168585  1.000000  0.073067  0.036621   
5    0.019233  0.063173  0.055768  0.128889  0.073067  1.000000  0.793300   
6    0.000000  0.039171  0.034579  0.061039  0.036621  0.793300  1.000000   
7    0.014958  0.049132  0.043372  0.438133  0.028413  0.415599  0.283677   
8    0.000000  0.029755  0.026267  0.377189  0.000000  0.248067  0.433314   
9    0.000000  0.068376  0.030180  0.026637  0.000000  0.110624  0.110889   
10   0.017554  0.057658  0.050899  0.117817  0.000000  0.108222  0.086988   
11   0.000000  0.000000  0.000000  0.000000  0.000000  0.054792  0.054924   
12   0.000000  0.052725  0.023272  0.043329  0.027345  0.153771  0.090772   
13   0.000000  0.141711  0.062550  0.055206  0.000000  0.057318  0.057455   
14   0.000000  0.146723  0.064762  0.096597  0.000000  0.000000  0.000000   
15   0.119483  0.105092  0.075362  0.151736  0.152560  0.033785  0.000000   
16   0.122262  0.150628  0.075913  0.131588  0.165700  0.071630  0.020811   
17   0.068207  0.046219  0.041803  0.064056  0.076267  0.086939  0.072253   
18   0.123652  0.094557  0.085014  0.135088  0.151644  0.045721  0.000000   
19   0.094756  0.064210  0.058075  0.088989  0.136931  0.020642  0.000000   
20   0.167289  0.113361  0.102530  0.157107  0.239923  0.036444  0.000000   
21   0.161624  0.061975  0.056054  0.085891  0.102265  0.019924  0.000000   
22   0.000000  0.038096  0.000000  0.000000  0.000000  0.000000  0.000000   
23   0.232133  0.097488  0.088590  0.131791  0.240527  0.018764  0.000000   
24   0.213119  0.236366  0.159756  0.222402  0.286231  0.128770  0.074130   
25   0.134941  0.155710  0.085112  0.125238  0.172297  0.130705  0.092770   
26   0.100178  0.063867  0.077389  0.103360  0.149572  0.027632  0.027698   
27   0.030272  0.100981  0.033482  0.072121  0.063547  0.140314  0.101554   
28   0.054320  0.068057  0.036053  0.049306  0.085293  0.021879  0.000000   
29   0.074164  0.237289  0.063539  0.076308  0.130436  0.000000  0.000000   
..        ...       ...       ...       ...       ...       ...       ...   
77   0.000000  0.033899  0.000000  0.042238  0.000000  0.084742  0.084945   
78   0.000000  0.000000  0.000000  0.000000  0.045620  0.043341  0.110508   
79   0.035557  0.030232  0.019664  0.034710  0.046143  0.000000  0.059663   
80   0.000000  0.000000  0.000000  0.021340  0.025606  0.169591  0.143230   
81   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
82   0.011627  0.101572  0.012859  0.011350  0.027238  0.000000  0.065008   
83   0.088931  0.229775  0.142020  0.149602  0.121024  0.038238  0.038329   
84   0.074059  0.097662  0.054140  0.061800  0.123044  0.080656  0.041320   
85   0.000000  0.000000  0.000000  0.000000  0.086239  0.000000  0.000000   
86   0.102697  0.024766  0.000000  0.000000  0.000000  0.067044  0.067205   
87   0.081845  0.029607  0.000000  0.000000  0.044851  0.080147  0.080339   
88   0.073876  0.071440  0.019737  0.017420  0.090937  0.124958  0.125257   
89   0.127590  0.032379  0.021060  0.037175  0.098470  0.135757  0.087862   
90   0.084485  0.033023  0.021479  0.037915  0.072775  0.149363  0.149720   
91   0.000000  0.042706  0.000000  0.000000  0.064696  0.063449  0.000000   
92   0.000000  0.000000  0.000000  0.054161  0.062514  0.141254  0.184639   
93   0.000000  0.000000  0.000000  0.047752  0.099391  0.059753  0.097849   
94   0.000000  0.000000  0.000000  0.072757  0.130105  0.121324  0.129853   
95   0.000000  0.032558  0.000000  0.000000  0.000000  0.044069  0.149913   
96   0.000000  0.028075  0.000000  0.060912  0.113088  0.315573  0.146874   
97   0.0